const root=document.querySelector('#root');
let lives=[
{id:'live_001',title:'ONE OK ROCK 2026 Tour',artist:'ONE OK ROCK',date:'2026-08-14',city:'东京',venue:'Tokyo Dome',memory:'全场亮灯的时候，我突然觉得自己真的来过这里。',ticketNo:'LIVE-0001'},
{id:'live_002',title:'SCIENCE FICTION TOUR',artist:'宇多田光',date:'2026-05-03',city:'东京',venue:'Zepp Haneda',memory:'副歌响起的时候，我忍不住想哭。',ticketNo:'LIVE-0002'},
{id:'live_003',title:'冬日回声',artist:'落日飞车',date:'2025-12-20',city:'上海',venue:'梅赛德斯-奔驰文化中心',memory:'散场后，外滩的风还是热的。',ticketNo:'LIVE-0003'},
{id:'live_004',title:'宇宙超有趣',artist:'告五人',date:'2025-10-02',city:'北京',venue:'国家体育馆',memory:'和陌生人一起唱到嗓子沙哑。',ticketNo:'LIVE-0004'},
{id:'live_005',title:'潮汐收藏家',artist:'椅子乐团',date:'2025-07-19',city:'台北',venue:'Legacy Taipei',memory:'鼓点落下的那一秒，雨也刚好停了。',ticketNo:'LIVE-0005'}];
let view={type:'home'}, modal=null, toast='';const coords={东京:[76,31],上海:[67,53],北京:[55,25],台北:[78,66],成都:[38,61],广州:[54,79]};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const cities=()=>Object.entries(lives.reduce((a,l)=>((a[l.city]??=[]).push(l),a),{})).map(([name,items])=>({name,items,venues:new Set(items.map(i=>i.venue)).size}));
function header(){return `<header><button class="brand" data-home><span class="logo">♫</span><span>Live 足迹</span></button><button class="add" data-add><span>＋</span> 添加演出</button></header>`}
function home(){let cs=cities(),venues=new Set(lives.map(l=>l.venue)).size,recent=[...lives].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);return `<section class="hero"><div><p class="eyebrow">MY LIVE ARCHIVE · 2025—2026</p><h1>把每一场 Live，<br><em>收藏在你的地图里。</em></h1><p class="intro">声音会散去，但那座城市、那个夜晚，值得被好好记住。</p><button class="hero-add" data-add>＋ 记下新的一场 <b>→</b></button></div><div class="doodle" aria-hidden="true"><span class="sun">✳</span><span class="speaker">◯<i>)))</i></span><span class="person">𐀪</span><span class="sound">♪</span><p>今晚<br>也要大声唱！</p></div></section><section class="stats-strip"><div><b>${String(lives.length).padStart(2,'0')}</b><span>场演出<br><i>LIVE SHOWS</i></span></div><div><b>${String(cs.length).padStart(2,'0')}</b><span>座城市<br><i>CITIES</i></span></div><div><b>${String(venues).padStart(2,'0')}</b><span>个场馆<br><i>VENUES</i></span></div><p>从第一声鼓点开始，<br>慢慢画出自己的现场地图。</p></section><section class="map-intro"><p class="eyebrow">01 · WHERE I'VE BEEN</p><h2>声音落在了<br><span>这些地方</span></h2><p>点开一座城市，看看那里收藏着哪些舞台和夜晚。</p></section><section class="map-wrap"><div class="map-head"><div><span class="scribble">我的 Live 地图</span><small>${cs.length} 座城市 · ${lives.length} 场演出</small></div><span class="hint">点击圆点，回到那个夜晚 ↘</span></div><div class="map"><div class="land land1"></div><div class="land land2"></div><div class="route"></div>${cs.map((c,i)=>{let p=coords[c.name]||[20+i*13,45];return `<button class="pin" style="left:${p[0]}%;top:${p[1]}%" data-city="${esc(c.name)}"><i></i><b>${esc(c.name)}</b><span>${c.items.length} 场</span></button>`}).join('')}<span class="map-note">♪ 每个点，都是一段<br>曾经很响亮的记忆</span></div></section><section class="city-grid">${cs.map((c,i)=>`<button class="city-card" data-city="${esc(c.name)}"><span>0${i+1}</span><h3>${esc(c.name)}</h3><p>${c.items.length} 场演出 · ${c.venues} 个场馆</p><b>去看看 →</b></button>`).join('')}</section><section class="recent"><div class="section-title"><div><p class="eyebrow">02 · RECENT MEMORIES</p><h2>最近收藏的<br><span>三个夜晚</span></h2></div><p>有些旋律忘了，<br>但身体还记得。</p></div><div class="recent-list">${recent.map(l=>`<button data-ticket="${l.id}"><span class="recent-date"><b>${l.date.slice(5).replace('-','.')}</b><i>${l.date.slice(0,4)}</i></span><span class="recent-copy"><small>${esc(l.city)} · ${esc(l.venue)}</small><strong>${esc(l.artist)}</strong><em>${esc(l.title)}</em></span><span class="recent-arrow">↗</span></button>`).join('')}</div></section><section class="home-cta"><span class="burst">✳</span><p class="eyebrow">DON'T LET IT FADE</p><h2>下一场，也别忘了<br>把它留下来。</h2><p>城市、场馆、歌声和一句只属于你的记忆。</p><button data-add>＋ 添加一场演出</button><span class="cta-note">不用登录 · 现在就记 ↗</span></section>`}
function cityPage(){let items=lives.filter(l=>l.city===view.city),vs=Object.entries(items.reduce((a,l)=>((a[l.venue]??=[]).push(l),a),{}));return `<section class="page"><p class="eyebrow">CITY ARCHIVE</p><h1>${esc(view.city)}<sup>↗</sup></h1><p class="page-sub">我在这里听过 ${items.length} 场演出，去过 ${vs.length} 个场馆。</p><div class="venue-list">${vs.map(([v,x],i)=>`<button data-venue="${esc(v)}"><span class="num">0${i+1}</span><span><small>VENUE</small><strong>${esc(v)}</strong></span><span class="count">${x.length} 场 <b>→</b></span></button>`).join('')}</div></section>`}
function venuePage(){let items=lives.filter(l=>l.city===view.city&&l.venue===view.venue);return `<section class="page"><p class="eyebrow">${esc(view.city)} · VENUE ARCHIVE</p><h1 class="venue-title">${esc(view.venue)}</h1><p class="page-sub">在这里收藏了 ${items.length} 个响亮的夜晚。</p><div class="tickets">${items.map((l,i)=>`<button class="ticket t${i%3}" data-ticket="${l.id}"><span class="ticket-side"><small>ADMIT ONE</small><b>${l.date.slice(5).replace('-',' / ')}</b><i>${l.ticketNo}</i></span><span class="ticket-main"><small>${esc(l.city)} · ${esc(l.venue)}</small><strong>${esc(l.artist)}</strong><em>${esc(l.title)}</em><span>查看这张票根 →</span></span></button>`).join('')}</div></section>`}
function addModal(){return `<div class="overlay"><form class="modal form" id="add-form"><button type="button" class="close" data-close>×</button><p class="eyebrow">NEW MEMORY</p><h2>记录这一场 Live</h2><div class="fields"><label>艺人 / 乐队<input required name="artist" placeholder="例如：ONE OK ROCK"></label><label>演出名称<input name="title" placeholder="例如：2026 Tour"></label><label>日期<input required type="date" name="date"></label><label>城市<input required name="city" placeholder="例如：东京"></label><label>场馆<input required name="venue" placeholder="例如：Tokyo Dome"></label><label class="wide">一句话记忆（选填）<textarea name="memory" placeholder="那天晚上，你最想留下什么？"></textarea></label><label class="wide upload">现场照片（原型占位）<input type="file" accept="image/*"><span>＋ 选择一张照片</span></label></div><button class="submit">收藏这场 Live <span>▰</span></button></form></div>`}
function detailModal(id){let l=lives.find(x=>x.id===id);return `<div class="overlay"><div class="modal detail"><button class="close" data-close>×</button><p class="eyebrow">ELECTRONIC TICKET</p><div class="big-ticket"><div><small>LIVE FOOTPRINT · ADMIT ONE</small><h2>${esc(l.artist)}</h2><p>${esc(l.title)}</p><blockquote>“${esc(l.memory||'那晚的声音，我还记得。')}”</blockquote></div><aside><span class="icon">◷</span><b>${l.date}</b><span class="icon">⌖</span><span>${esc(l.city)}<br>${esc(l.venue)}</span><i>${l.ticketNo}</i></aside></div></div></div>`}
function render(){let body=view.type==='home'?home():view.type==='city'?cityPage():venuePage();let back=view.type==='home'?'':`<button class="back" data-back>← 返回${view.type==='venue'?'城市':'地图'}</button>`;let pop=modal==='add'?addModal():modal?detailModal(modal):'';root.innerHTML=`<main>${header()}${body}${back}${pop}${toast?`<div class="toast">✓ ${esc(toast)}</div>`:''}</main>`}
root.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.matches('[data-home]')){view={type:'home'};modal=null}if(b.matches('[data-add]'))modal='add';if(b.matches('[data-close]'))modal=null;if(b.dataset.city)view={type:'city',city:b.dataset.city};if(b.dataset.venue)view={type:'venue',city:view.city,venue:b.dataset.venue};if(b.dataset.ticket)modal=b.dataset.ticket;if(b.matches('[data-back]'))view=view.type==='venue'?{type:'city',city:view.city}:{type:'home'};render()});
root.addEventListener('submit',e=>{if(e.target.id!=='add-form')return;e.preventDefault();let f=new FormData(e.target),n=lives.length+1,artist=f.get('artist'),city=f.get('city'),venue=f.get('venue');lives.push({id:`live_${String(n).padStart(3,'0')}`,title:f.get('title')||`${artist} Live`,artist,date:f.get('date'),city,venue,memory:f.get('memory'),ticketNo:`LIVE-${String(n).padStart(4,'0')}`});view={type:'city',city};modal=null;toast=`已收藏 ${artist} 的这场 Live`;render();setTimeout(()=>{toast='';render()},2600)});render();
